name: Automerge PRs raised from `t`

on: pull_request

jobs:
  automerge:
    name: Merge pull request
    runs-on: [ubuntu-latest]
    if: github.base_ref == 'master' && github.head_ref == 't'
    steps:
      - name: Merge via the API
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
