name: create-run-and-update-to-in-progress-then-completed
on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Create check run and update to neutral
      uses: actions/github-script@v4.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        debug: true
        previews: 'antiope-preview'
        script: |
        
          // Create the check run. Automatically sets to `status` to `queued`.
          const { data: checkRun } = await github.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: "Actions-created check run by workflow in actions-packages-examples/github-script__playground",
            head_sha: context.payload.after
          })
          
          // Update the check run status to `in_progress`.
          const { data: updatedCheckRun } = await github.checks.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            check_run_id: checkRun.id,
            status: "in_progress"
          })
          
          // Finally, update the check run conclusion to `success`, which automatically updates status to `completed`.
          const { data: completedCheckRun } = await github.checks.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            check_run_id: updatedCheckRun.id,
            conclusion: "success"
          })
          
          // Render the cached response.
          console.log(completedCheckRun)
