name: Delete branch using actions

on: watch

jobs:
  first_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@0.4.0
      if: github.actor == 'francisfuzz'

      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        script: |
          
          // https://octokit.github.io/rest.js/#octokit-routes-git-delete-ref
          const result = await github..git.deleteRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "bot-target"
          })
          
          console.log(result)
