name: Create and update check run on push
on: push

jobs:
  create-check:

    runs-on: ubuntu-latest

    steps:
    - name: create and update
      uses: actions/github-script@v4.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        debug: true
        previews: 'antiope-preview'
        script: |
          const { data: checkRun } = await github.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: "Actions-created check run by francisfuzz",
            head_sha: context.payload.after
          })
          
          console.log(checkRun)
          
