# This is a basic workflow to help you get started with Actions

name: Meta

on: repository_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.1, 1.1.0, 2, 2.0, 2.0.0]

    # Fetch the rate limit at each version of actions/github-script
    steps:
    - uses: actions/github-script@${{ matrix.node }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |

          // https://octokit.github.io/rest.js/v17#rate-limit-get
          const result = await github.rateLimit.get()
          console.log(result)
