# Workflow for using recent versions of `actions/github-script`.
# Invocation: `curl -v -H "Authorization: token $TOKEN" "https://api.github.com/repos/actions-packages-examples/github-script__playground/dispatches" -X POST -d '{"event_type":"trigger"}'`
name: Meta

on: repository_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Fetch the rate limit at each version of actions/github-script
    steps:
    - uses: actions/github-script@v1.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |

          // https://octokit.github.io/rest.js/v17#rate-limit-get
          const result = await github.rateLimit.get()
          console.log(result)

    - uses: actions/github-script@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |

          // https://octokit.github.io/rest.js/v17#rate-limit-get
          const result = await github.rateLimit.get()
          console.log(result)
