name: Update now file on watch

on: watch

jobs:
  first_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@1.1.0
      if: github.actor == 'francisfuzz'

      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        script: |
          const now = Date.now().toString()
          const nowEncoded = new Buffer(now).toString('base64')

          // https://octokit.github.io/rest.js/v17#repos-create-or-update-file
          const result = await github.repos.createOrUpdateFile({
            owner: context.repo.owner,
            repo: context.repo.repo,
            path: 'now.md',
            message: `updated: ${now}`,
            content: `${nowEncoded}`
          })
          
          console.log(result)
