name: Update now file on watch

on: watch

jobs:
  first_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v2.0.0
      if: github.actor == 'francisfuzz'

      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        script: |
          const now = Date.now().toString()
          const nowEncoded = Buffer.from(now).toString('base64')
          
          // Fetch the file, caching its `sha` value (required for updating a file)
          const { data: sha } = await github.repos.getContent({
            owner: context.repo.owner,
            repo: context.repo.repo,          
            path: 'now.md'
          })

          console.log(sha)

          // https://octokit.github.io/rest.js/v17#repos-create-or-update-file
          const result = await github.repos.createOrUpdateFile({
            owner: context.repo.owner,
            repo: context.repo.repo,
            path: 'now.md',
            message: `updated: now.md`,
            content: `${nowEncoded}`,
            sha: `${sha}`
          })
          
          console.log(result)
